### ISSUE TITLE
Textkleur en layout klopt niet

### ISSUE THREAD

**Issue by klaasscho1** [LaraPirkner/Gehacked-d1b48e37#2]
Goed bezig! Er zijn nog maar een paar puntjes die verbeterd moeten worden:
- De kleur van de content van de tabel is grijs, maar zou zwart moeten zijn.
- De laatste kolom van de tabel verschijnt onder de rest van de content bij mij. Zorg dat deze altijd naast de rest van de kolommen staat!

Verder goed werk Lara, ga zo door 💪

<img width="1440" alt="Screen Shot 2020-03-19 at 2 58 27 PM" src="https://user-images.githubusercontent.com/4458455/77075097-1c898c80-69f2-11ea-896c-fc47840e9eab.png">

**Comment by LaraPirkner** [comment]
@klaasscho1 het klopt wel dat de laatste kolom er onder staat het ligt aan de grote van uw scherm
![image](https://user-images.githubusercontent.com/54847633/77147947-c6b6f200-6a8e-11ea-91f4-f5cc50152cc8.png)
mijn scherm op mijn laptop is ook 1500 ofzo maar op 2000 staan ze naast elkaar. Ik heb het zo gemaakt dat het er onder komt te staan op de verschillende scherm grootes om het op die manier responsive te  maken. 
en de  kleur fix ik strakies wel.
